### ISSUE TITLE
Comments as of 105eaf357b (2016-02-17)

### ISSUE THREAD

**Issue by gvwilson** [dwinston/mongo-novice-materials#1]
-  [x] Please tackle setup/installation instructions next, so that I can test them here.
  - [x] Make sure to include instructions for Windows!
- [x] Why bother to zip the starting .json? Why not just download the .json?
- [x] Don't explain how Python `print` works - if they don't know a little Python, they're probably not going to be able to follow the rest of the lesson. (Or do you disagree?)
- [x] Whoa - railroad diagrams? I don't think the audience will appreciate them as much as we do :-) How about examples instead? Or examples and counter-examples (i.e., a few things that _aren't_ valid syntax)?
- [x] "We don't _need_ to care." Why not?
- [x] If you `print(result.inserted_id.generation_time)` is the output more readable (e.g., doesn't have the timezone object splatted out)?
- [x] "something special is going on" - I won't know what this means if I'm a novice
- [x] Someone actually _was_ struck and killed by a meteor a couple of weeks ago, you know...

**Comment by dwinston** [comment]
Setup instructions as of 33e87299339c32f4ce1c57134ab384c2932a2742
