### ISSUE TITLE
use a smaller DB, smaller objects and dump results of queries to see what is being returned

### ISSUE THREAD

**Issue by shreddd** [dwinston/mongo-novice-materials#10]

**Comment by shreddd** [comment]
alternately start using print_a_few_ type examples early on.

**Comment by dwinston** [comment]
Use of mongo shell means results of queries are streamed immediately, i.e. no need to "draw from" a cursor as with pymongo, and only a few results are printed at a time. Also, objects may be easier to inspect with `DBQuery.prototype._prettyShell = true` (introduced in the sorting topic, but perhaps I'll put it in earlier). Closing for now.
