### ISSUE TITLE
Explain that mongo has autocreate magic 

### ISSUE THREAD

**Issue by shreddd** [dwinston/mongo-novice-materials#7]
clarify that db.foo gets automatically created but this is a pymongo specific feature

novice python users may not get this idiom. explain that you just choose an arbitrary name (without spending too long on details).

**Comment by dwinston** [comment]
Same principle applies in the mongo shell / with javascript. Perhaps less of an issue b/c using `mongoimport`, so db/collection name will be set explicitly on the command line.
